name: CI
on: push
jobs:
  build:
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v2
    - name: change to backend dir
      run: cd backend
    - name: Install modules
      run: yarn
    - name: Run tests
      run: yarn test